import os
import re

src_dir = "src"
output_file = "submission.rs"

modules = [
    ("bitboard", "bitboard.rs"),
    ("types", "types.rs"),
    ("mquality", "mquality.rs"),
    ("dataloader", "dataloader.rs"),
    ("board", "board.rs"),
    ("eval", "eval.rs"),
    ("movegen", "movegen.rs"),
    ("tt", "tt.rs"),
    ("mcts", "mcts.rs"),
    ("timeman", "timeman.rs"),
]

module_extra_imports = {
    "mquality": ["use std::convert::TryInto;"],
    "dataloader": ["use std::convert::TryInto;"],
    "tt": ["use std::convert::TryInto;"],
}

def indent_content(content, indent="    "):
    return "\n".join(indent + line if line.strip() else "" for line in content.splitlines())

def read_file(path, remove_patterns=None):
    if not os.path.exists(path):
        return ""
    with open(path, "r", encoding="utf-8") as f:
        content = f.read()
    if remove_patterns:
        for pattern in remove_patterns:
            content = re.sub(pattern, "", content)
    return content

lines = [
    "// Generated by merge.py",
    "// Do not edit by hand; edit src/ instead.",
    "#![allow(dead_code, unused_imports)]",
    ""
]

# --- Flat modules ---
for mod_name, filename in modules:
    path = os.path.join(src_dir, filename)
    if os.path.exists(path):
        lines.append(f"// --- src/{filename} ---")
        lines.append(f"pub mod {mod_name} {{")
        for import_line in module_extra_imports.get(mod_name, []):
            lines.append(f"    {import_line}")
        content = read_file(path)
        lines.append(indent_content(content))
        lines.append("}")
        lines.append("")

# --- src/search/ ---
search_dir = os.path.join(src_dir, "search")
if os.path.exists(search_dir):
    lines.append("// --- src/search ---")
    lines.append("pub mod search {")

    # endgame was moved to end_game/; not in search anymore
    search_children = [
        ("result", "result.rs"),
        ("ordering", "ordering.rs"),
        ("pruning", "pruning.rs"),
        ("tactics", "tactics.rs"),
        ("root", "root.rs"),
        ("negamax", "negamax.rs"),
    ]

    for mod_name, filename in search_children:
        path = os.path.join(search_dir, filename)
        if os.path.exists(path):
            lines.append(f"    pub mod {mod_name} {{")
            lines.append(indent_content(read_file(path), "        "))
            lines.append("    }")
            lines.append("")

    search_mod_path = os.path.join(search_dir, "mod.rs")
    if os.path.exists(search_mod_path):
        search_mod_content = read_file(
            search_mod_path,
            [
                r"pub mod result;\s*",
                r"pub mod ordering;\s*",
                r"pub mod pruning;\s*",
                r"pub mod tactics;\s*",
                r"pub mod root;\s*",
                r"pub mod negamax;\s*",
            ],
        )
        search_mod_content = search_mod_content.replace("pub use result::{", "pub use self::result::{")
        lines.append(indent_content(search_mod_content))
    lines.append("}")
    lines.append("")

# --- src/opening/ ---
opening_dir = os.path.join(src_dir, "opening")
if os.path.exists(opening_dir):
    lines.append("// --- src/opening ---")
    lines.append("pub mod opening {")

    # stealth and traps are submodules (use super:: in second.rs before merging, change to crate::)
    stealth_content = read_file(os.path.join(opening_dir, "stealth.rs"))
    traps_content = read_file(os.path.join(opening_dir, "traps.rs"))
    first_content = read_file(os.path.join(opening_dir, "first.rs"))
    second_content = read_file(
        os.path.join(opening_dir, "second.rs"),
        [r"use super::stealth;", r"use super::traps;"],
    )
    ordering_content = read_file(os.path.join(opening_dir, "ordering.rs"))
    side_content = read_file(os.path.join(opening_dir, "side.rs"), [
        r"use super::first::",
        r"use super::second::",
    ])

    # stealth module
    lines.append("    pub mod stealth {")
    lines.append(indent_content(stealth_content, "        "))
    lines.append("    }")
    lines.append("")

    # traps module
    lines.append("    pub mod traps {")
    lines.append(indent_content(traps_content, "        "))
    lines.append("    }")
    lines.append("")

    # first module
    lines.append("    pub mod first {")
    lines.append(indent_content(first_content, "        "))
    lines.append("    }")
    lines.append("")

    # second module (needs stealth/traps to be in scope)
    lines.append("    pub mod second {")
    # add use statements that second.rs originally had but got removed
    second_inner = "        use crate::opening::stealth;\n        use crate::opening::traps;\n" + indent_content(second_content, "        ")
    lines.append(second_inner)
    lines.append("    }")
    lines.append("")

    # ordering module
    lines.append("    pub mod ordering {")
    lines.append(indent_content(ordering_content, "        "))
    lines.append("    }")
    lines.append("")

    # side.rs as a module (needs first/second in scope)
    lines.append("    pub mod side {")
    side_patched = side_content.replace(
        "super::first::FirstSideTuning",
        "crate::opening::first::FirstSideTuning"
    ).replace(
        "super::second::SecondSideTuning",
        "crate::opening::second::SecondSideTuning"
    )
    lines.append(indent_content(side_patched, "        "))
    lines.append("    }")
    lines.append("")

    # mod.rs
    op_mod_content = read_file(
        os.path.join(opening_dir, "mod.rs"),
        [
            r"pub mod first;\s*",
            r"pub mod second;\s*",
            r"pub mod stealth;\s*",
            r"pub mod traps;\s*",
            r"pub mod ordering;\s*",
            r"mod side;\s*",
        ],
    )
    # Fix self:: references for the merged context
    op_mod_content = op_mod_content.replace("pub use first::", "pub use self::first::")
    op_mod_content = op_mod_content.replace("pub use second::", "pub use self::second::")
    op_mod_content = op_mod_content.replace("pub use side::", "pub use self::side::")
    lines.append(indent_content(op_mod_content))
    lines.append("}")
    lines.append("")

# --- src/mid_game/ ---
mid_game_dir = os.path.join(src_dir, "mid_game")
if os.path.exists(mid_game_dir):
    lines.append("// --- src/mid_game ---")
    lines.append("pub mod mid_game {")

    ordering_content = read_file(os.path.join(mid_game_dir, "ordering.rs"))
    lines.append("    pub mod ordering {")
    lines.append(indent_content(ordering_content, "        "))
    lines.append("    }")
    lines.append("")

    mg_mod_content = read_file(
        os.path.join(mid_game_dir, "mod.rs"),
        [r"pub mod ordering;\s*"],
    )
    lines.append(indent_content(mg_mod_content))
    lines.append("}")
    lines.append("")

# --- src/end_game/ ---
end_game_dir = os.path.join(src_dir, "end_game")
if os.path.exists(end_game_dir):
    lines.append("// --- src/end_game ---")
    lines.append("pub mod end_game {")

    search_content = read_file(os.path.join(end_game_dir, "search.rs"))
    ordering_content = read_file(os.path.join(end_game_dir, "ordering.rs"))

    lines.append("    pub mod search {")
    lines.append(indent_content(search_content, "        "))
    lines.append("    }")
    lines.append("")

    lines.append("    pub mod ordering {")
    lines.append(indent_content(ordering_content, "        "))
    lines.append("    }")
    lines.append("")

    eg_mod_content = read_file(
        os.path.join(end_game_dir, "mod.rs"),
        [r"pub mod search;\s*", r"pub mod ordering;\s*"],
    )
    lines.append(indent_content(eg_mod_content))
    lines.append("}")
    lines.append("")

# --- src/side/ (now just re-exports from opening) ---
side_dir = os.path.join(src_dir, "side")
if os.path.exists(side_dir):
    lines.append("// --- src/side ---")
    lines.append("pub mod side {")
    side_mod_content = read_file(os.path.join(side_dir, "mod.rs"))
    lines.append(indent_content(side_mod_content))
    lines.append("}")
    lines.append("")

# --- src/main.rs ---
main_path = os.path.join(src_dir, "main.rs")
if os.path.exists(main_path):
    lines.append("// --- src/main.rs ---")
    with open(main_path, "r", encoding="utf-8") as f:
        content = f.read()
        content = content.replace("use mushroom_bot::", "use crate::")
        content = content.replace("mushroom_bot::", "crate::")
        lines.append(content)

with open(output_file, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

print(f"Successfully generated {output_file}")
